/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as pagesRouteImport } from './routes/(pages)/route'
import { Route as pagesIndexImport } from './routes/(pages)/index'
import { Route as pagesProfileIndexImport } from './routes/(pages)/profile/index'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'

// Create/Update Routes

const pagesRouteRoute = pagesRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRoute,
} as any)

const pagesIndexRoute = pagesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pagesRouteRoute,
} as any)

const pagesProfileIndexRoute = pagesProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => pagesRouteRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)': {
      id: '/(pages)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesRouteImport
      parentRoute: typeof rootRoute
    }
    '/(pages)/': {
      id: '/(pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesIndexImport
      parentRoute: typeof pagesRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(pages)/profile/': {
      id: '/(pages)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof pagesProfileIndexImport
      parentRoute: typeof pagesRouteImport
    }
  }
}

// Create and export the route tree

interface pagesRouteRouteChildren {
  pagesIndexRoute: typeof pagesIndexRoute
  pagesProfileIndexRoute: typeof pagesProfileIndexRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesIndexRoute: pagesIndexRoute,
  pagesProfileIndexRoute: pagesProfileIndexRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof pagesIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/profile': typeof pagesProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof pagesIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/profile': typeof pagesProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/(pages)/': typeof pagesIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(pages)/profile/': typeof pagesProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/profile'
  id:
    | '__root__'
    | '/(pages)'
    | '/(pages)/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(pages)/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  pagesRouteRoute: pagesRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(pages)",
        "/(auth)/login/",
        "/(auth)/register/"
      ]
    },
    "/(pages)": {
      "filePath": "(pages)/route.tsx",
      "children": [
        "/(pages)/",
        "/(pages)/profile/"
      ]
    },
    "/(pages)/": {
      "filePath": "(pages)/index.tsx",
      "parent": "/(pages)"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    },
    "/(pages)/profile/": {
      "filePath": "(pages)/profile/index.tsx",
      "parent": "/(pages)"
    }
  }
}
ROUTE_MANIFEST_END */
